### ISSUE TITLE
Getting Blank white screen

### ISSUE THREAD

**Issue by Vigneshwaran86** [codezri/neutralinojs-react#4]
Hello ,

After react build, while enter the command "neu run" is displaying window screen with blank white screen. It's not loaded into react component page at this window panel.
Kindly help me for this. Thanks!!!

**Comment by mp3846** [comment]
Installing webview2 may solve your issue
check the info section [here](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/#step-1-creating-a-new-app)

**Comment by shalithasuranga** [comment]
Hello.. closing this issue since a working solution was mentioned above .. Thanks
