### ISSUE TITLE
How used API Neutralino from React?

### ISSUE THREAD

**Issue by Alexygen** [codezri/neutralinojs-react#5]
I create application and want use Tray menu, but from React is not working! May be I do wrong!
I get message "neu: INFO neutralino-mac_x64 was stopped with success code 0" and app crashes(((

OS: macOS Monterey 12.5

import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import App from './App'

const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(<App />)

let tray = {
    icon: '/myapp-react/public/tray.png',
    menuItems: [
        {
            id: 'checkbox',
            text: 'Checkbox',
        },
        {
            id: 'about',
            text: 'About',
        },
        {
            id: 'sep',
            text: '-',
        },
        {
            id: 'quit',
            text: 'Quit',
        },
    ],
}

const onTrayMenuItemClicked = async (menuItem) => {
    switch (menuItem.id) {
        case 'checkbox':
            let item = tray.menuItem.find((item) => item.id === 'checkbox')
            item.isChecked = !menuItem.isChecked
            await window.Neutralino.os.setTray(tray)
            break
        case 'about':
            await window.Neutralino.os.showMessageBox({
                title: 'About',
                content: 'Text',
                type: 'INFO',
            })
            break
        case 'quit':
            await window.Neutralino.app.exit()
            break
        default:
            break
    }
}

const showTray = async () => {
    await window.Neutralino.events.on(
        'trayMenuItemClicked',
        onTrayMenuItemClicked
    )
    await window.Neutralino.os.setTray(tray)
}

showTray()

window.Neutralino.init()

**Comment by shalithasuranga** [comment]
Hello @Alexygen, please check [this](https://neutralino.js.org/docs/getting-started/using-frontend-libraries) tutorial or use the pre-developed React template (from this repo). Also, please note that we also have an open issue (https://github.com/neutralinojs/neutralinojs/issues/615) for the framework issue related to `os.setTray`. Thanks :tada:
