### ISSUE TITLE
Timeout exceeded while waiting port 3000

### ISSUE THREAD

**Issue by Karakoukie** [codezri/neutralinojs-react#7]
Just downloaded the project and the run command can't be launched on port 3000 but the react app can.

**Comment by devanshkansagra** [comment]
No, It works on my machine

https://ibb.co/c2hfR7Z

Also there is no error in the browser

https://ibb.co/BCgHDyt

Your issue might be resolved  by running different node version
Use NVM to use different node versions

Hope it helps

**Comment by shalithasuranga** [comment]
Hello.. this issue was fixed in the latest CLI version. Thanks :tada:

**Comment by CiberNin** [comment]
Was it though?
```
$ cd myapp && neu run
neu: INFO Running devCommand: npm run start...

> myapp-react@0.1.0 start
> cross-env BROWSER=none react-scripts start

neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: INFO App will be launched when http://localhost:3000 on port 3000 is ready...
neu: ERRR Timeout exceeded while waiting till local TCP port: 3000
```
I've been trying everything I can think of for the last six hours and I can't get past this. Latest version of everything.

**Comment by ToddAlvord** [comment]
Im still having the same issue as @CiberNin
